# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: types.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import Dict, List

import betterproto


@dataclass
class EventInfo(betterproto.Message):
    """Common event info"""

    name: str = betterproto.string_field(1)
    code: str = betterproto.string_field(2)
    msg: str = betterproto.string_field(3)
    level: str = betterproto.string_field(4)
    invocation_id: str = betterproto.string_field(5)
    pid: int = betterproto.int32_field(6)
    thread: str = betterproto.string_field(7)
    ts: datetime = betterproto.message_field(8)


@dataclass
class GenericMessage(betterproto.Message):
    """GenericMessage, used for deserializing only"""

    info: EventInfo = betterproto.message_field(1)


@dataclass
class MainReportVersion(betterproto.Message):
    """MainReportVersion"""

    info: EventInfo = betterproto.message_field(1)
    version: str = betterproto.string_field(2)


@dataclass
class MainReportArgs(betterproto.Message):
    """MainReportArgs"""

    info: EventInfo = betterproto.message_field(1)
    args: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass
class RollbackFailed(betterproto.Message):
    """RollbackFailed"""

    info: EventInfo = betterproto.message_field(1)
    conn_name: str = betterproto.string_field(2)
    exc_info: str = betterproto.string_field(3)


@dataclass
class MainEncounteredError(betterproto.Message):
    """MainEncounteredError"""

    info: EventInfo = betterproto.message_field(1)
    exc: str = betterproto.string_field(2)


@dataclass
class PluginLoadError(betterproto.Message):
    """PluginLoadError"""

    info: EventInfo = betterproto.message_field(1)
    exc_info: str = betterproto.string_field(2)


@dataclass
class ParsedFileLoadFailed(betterproto.Message):
    """ParsedFileLoadFailed"""

    info: EventInfo = betterproto.message_field(1)
    path: str = betterproto.string_field(2)
    exc: str = betterproto.string_field(3)
    exc_info: str = betterproto.string_field(4)


@dataclass
class CatchableExceptionOnRun(betterproto.Message):
    """CatchableExceptionOnRun"""

    info: EventInfo = betterproto.message_field(1)
    exc: str = betterproto.string_field(2)
    exc_info: str = betterproto.string_field(3)


@dataclass
class PrintDebugStackTrace(betterproto.Message):
    """PrintDebugStackTrace"""

    info: EventInfo = betterproto.message_field(1)
    exc_info: str = betterproto.string_field(2)


@dataclass
class NodeConnectionReleaseError(betterproto.Message):
    """NodeConnectionReleaseError"""

    info: EventInfo = betterproto.message_field(1)
    node_name: str = betterproto.string_field(2)
    exc: str = betterproto.string_field(3)
    exc_info: str = betterproto.string_field(4)


@dataclass
class SQLRunnerException(betterproto.Message):
    """SQLRunnerException"""

    info: EventInfo = betterproto.message_field(1)
    exc: str = betterproto.string_field(2)
    exc_info: str = betterproto.string_field(3)


@dataclass
class TrackingInitializeFailure(betterproto.Message):
    """TrackingInitializeFailure"""

    info: EventInfo = betterproto.message_field(1)
    exc_info: str = betterproto.string_field(2)


@dataclass
class AdapterEventDebug(betterproto.Message):
    """AdapterEventDebug"""

    info: EventInfo = betterproto.message_field(1)
    name: str = betterproto.string_field(2)
    base_msg: str = betterproto.string_field(3)
    args: List[str] = betterproto.string_field(4)


@dataclass
class AdapterEventInfo(betterproto.Message):
    """AdapterEventInfo"""

    info: EventInfo = betterproto.message_field(1)
    name: str = betterproto.string_field(2)
    base_msg: str = betterproto.string_field(3)
    args: List[str] = betterproto.string_field(4)


@dataclass
class AdapterEventWarning(betterproto.Message):
    """AdapterEventWarning"""

    info: EventInfo = betterproto.message_field(1)
    name: str = betterproto.string_field(2)
    base_msg: str = betterproto.string_field(3)
    args: List[str] = betterproto.string_field(4)


@dataclass
class AdapterEventError(betterproto.Message):
    """E004"""

    info: EventInfo = betterproto.message_field(1)
    name: str = betterproto.string_field(2)
    base_msg: str = betterproto.string_field(3)
    args: List[str] = betterproto.string_field(4)
    exc_info: str = betterproto.string_field(5)
